# Generated by Django 3.2.9 on 2022-04-20 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bank_image', models.ImageField(upload_to='prop/%Y/%m/%d')),
                ('Bank_name', models.CharField(max_length=50)),
                ('Phone_number', models.CharField(max_length=50)),
                ('Rate', models.CharField(max_length=50)),
                ('Tenure', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Properti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Rent', 'Rent'), ('Sale', 'Sale'), ('Auction', 'Auction')], max_length=50)),
                ('ptype', models.CharField(choices=[('Home', 'Home'), ('Land', 'Land'), ('Room', 'Room')], max_length=50)),
                ('area', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('number_of_rooms', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('has_installment', models.BooleanField(default=False)),
                ('has_insurance', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=455)),
                ('garden', models.BooleanField(default=False)),
                ('garage', models.BooleanField(default=False)),
                ('swimming_pool', models.BooleanField(default=False)),
                ('bathtub', models.BooleanField(default=False)),
                ('ac', models.BooleanField(default=False)),
                ('internet', models.BooleanField(default=False)),
                ('play_ground', models.BooleanField(default=False)),
                ('video', models.URLField(blank=True, null=True)),
                ('photo', models.ImageField(upload_to='prop/%Y/%m/%d')),
                ('paid', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('seodescription', models.TextField(blank=True)),
                ('bidding_start_time', models.DateTimeField(blank=True, null=True)),
                ('bidding_end_time', models.DateField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'ordering': ['-paid', '-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Bidders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_amount', models.FloatField()),
                ('properti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidders_prop', to='realestate.properti')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bidder_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-bid_amount'],
            },
        ),
        migrations.CreateModel(
            name='ApplyAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Agency_name', models.CharField(max_length=50)),
                ('Agency_Location', models.CharField(max_length=50)),
                ('Agency_Contact', models.CharField(max_length=50)),
                ('Agency_Email', models.EmailField(max_length=254, unique=True)),
                ('Agency_Description', models.CharField(max_length=255)),
                ('Agency_logo', models.ImageField(blank=True, null=True, upload_to='prop/%Y/%m/%d')),
                ('is_approved', models.BooleanField(default=False)),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgentRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('agent', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating_of_agent', to='realestate.applyagent')),
                ('rating_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_rater', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
