# Generated by Django 3.2.9 on 2022-03-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='agent',
            field=models.BooleanField(default=False),
        ),
    ]
